---
# run with -e "uu_c3_appbox_version=2.8.1"
- name: Download and install C3
  hosts: syshost
  become: true
  vars:
    uu_c3_appbox_version: 2.9.3
    uu_login_file_path: '/opt/installation/login'
    uu_c3_base_folder: '/opt/installation/uu_c3'
  roles:
    - uu_c3
