---
- name: Copy latest runtimestacks
  hosts: syshost
  become: true
  tasks:
    - name: Copy runtimestack
      copy:
        src: ~/work/temp/uucloud/uu_c3_centos_stack-7.1.zip
        dest: /opt/installation/uu_c3_centos_stack-7.1.zip

    - name: Create runtimestack folder
      file:
        path: /opt/installation/uu_c3_centos_stack-7.1/
        state: directory

    - name: Unarchive runtimestack
      unarchive:
        src: /opt/installation/uu_c3_centos_stack-7.1.zip
        dest: /opt/installation/uu_c3_centos_stack-7.1/
        remote_src: yes