---
- debug:
    msg: "{{ subapps }}"
- name: Generate {{ environment_name }}_secrets.rb
  template:
    src: secrets.rb.j2
    dest: "../../../roles/uu_or/templates/{{ environment_name | lower }}_secrets.rb"
