---
- name: Check if the image is already built in local Docker repository
  command: docker images -q {{ registry_hostname }}:{{ registry_port }}/uu_c3-cmd:{{ uu_c3_appbox_version }}
  register: image_exists

- name: Fail when image already exists
  fail:
    msg: C3 with version {{ uu_c3_appbox_version }} already exists in local Docker repository. Image ID {{ image_exists.stdout }}.
  when: image_exists.stdout_lines|length > 0

- name: Create appbox folder
  file:
    path: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}"
    state: directory

- name: Create access codes file
  template:
    src: login
    dest: "{{ uu_login_file_path }}"

- name: Create ruby script for download appbox
  template:
    src: DownloadFilesFromUU.rb
    dest: "{{ uu_c3_base_folder }}/DownloadFilesFromUU.rb"

- name: Run ruby script for appbox download
  command: ruby {{ uu_c3_base_folder }}/DownloadFilesFromUU.rb

- name: Delete access codes file
  file:
    path: "{{ uu_login_file_path }}"
    state: absent

- name: Unarchive uu_c3-dockerfiles-{{ uu_c3_appbox_version }}.zip
  unarchive:
    src: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/uu_c3-dockerfiles-{{ uu_c3_appbox_version }}.zip"
    dest: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/"
    remote_src: yes

- name: Copy C3 war file to build folder
  copy:
    src: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/uu_c3-cmd-{{ uu_c3_appbox_version }}.war"
    dest: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/c3/uu_c3-cmd.war"
    remote_src: yes

- name: Copy C3 scripts file to build folder
  copy:
    src: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/uu_c3-scripts-{{ uu_c3_appbox_version }}.zip"
    dest: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/c3/uu_c3-scripts.zip"
    remote_src: yes

- name: Replace REPO_PREFIX
  lineinfile:
    path: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/{{ item }}"
    regexp: '^REPO_PREFIX'
    line: 'REPO_PREFIX="{{ registry_hostname }}:5000"'
  with_items:
    - _push_c3_images.sh
    - _tag_c3_images.sh
#
- name: Replace tag to {{ uu_c3_appbox_version }}
  replace:
    path: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/{{ item }}"
    regexp: "latest"
    replace: "{{ uu_c3_appbox_version }}"
  with_items:
    - build_uu_c3-cmd.sh
    - _push_c3_images.sh
    - _tag_c3_images.sh

- name: Copy shared files
  copy:
    src: "/opt/installation/shared-files/{{ item }}"
    dest: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/shared-files/{{ item }}"
    remote_src: yes
  with_items:
  - jdk-8u144-linux-i586.rpm
  - uu-client.properties

- name: Copy UnlimitedJCEPolicyJDK8
  copy:
    src: "/opt/installation/shared-files/UnlimitedJCEPolicyJDK8"
    dest: "{{ uu_c3_base_folder }}/{{ uu_c3_appbox_version }}/docker/shared-files/"
    remote_src: yes
